#!/bin/sh

bspc rule -r "*"


#### Desktops
bspc monitor -d      爵 漣 

bspc config split_ratio                       0.5

bspc config top_padding                         24
bspc config bottom_padding                       0
bspc config left_padding                         0
bspc config right_padding                        0

bspc config borderless_monocle               false
bspc config gapless_monocle                  false
bspc config top_monocle_padding                  0
bspc config bottom_monocle_padding               0
bspc config left_monocle_padding                 0
bspc config right_monocle_padding                0

bspc config normal_border_color          '#918175'
bspc config active_border_color          '#D0BFA1'
bspc config focused_border_color         '#FED06E'
bspc config presel_feedback_color        '#918175'


#### Apps
bspc rule -a people             desktop='2'  follow=on
bspc rule -a terminal           desktop='3'  follow=on
bspc rule -a main               desktop='4'  follow=on
bspc rule -a firefox            desktop='5'  follow=on
bspc rule -a Gimp               desktop='6'  follow=on
bspc rule -a Blender            desktop='6'  follow=on
bspc rule -a Godot              desktop='7'  follow=on
bspc rule -a Steam              desktop='8'  follow=on
bspc rule -a Lutris             desktop='8'  follow=on
bspc rule -a retroarch          desktop='8'  follow=on
bspc rule -a minecraft          desktop='8'  follow=on
bspc rule -a Screenkey          manage=off

#### Keybinding
bspc config focus_follows_pointer            false
bspc config pointer_action1                   move
bspc config pointer_action2          resize_corner
bspc config pointer_action3          resize_corner


#### Autostarts
xwallpaper --zoom "$HOME/.local/share/wallpapers/indoor/background-min.png"
# xwallpaper --zoom "$HOME/.local/share/wallpapers/forest/burgeon-by-i5yal.png"
setxkbmap && xmodmap .Xmodmap
dwsb layout a169 ^1
dwsb layout a169 ^2
dwsb layout a43  ^3
dwsb layout a169 ^4
dwsb layout full ^5
dwsb layout full ^6
dwsb layout full ^7
dwsb layout a169 ^8

killall picom       ; picom --experimental-backends &
killall polybar     ; polybar bar &
killall redshift    ; redshift -P &
killall dunst       ; dunst &
killall sxhkd       ; sxhkd &
killall greenclip   ; greenclip daemon &
killall ibus-daemon ; ibus-daemon -rdx &
killall mpd         ; mpd &
