.local/share/theme.cat:
  type: file
  url: https://raw.githubusercontent.com/NNBnh/da-one/main/da-one-sea.cat
.local/share/gitalias.txt:
  type: file
  url: https://raw.githubusercontent.com/GitAlias/gitalias/main/gitalias.txt
