#!/bin/sh

# Install -----------------------------------------------------------------------------------------

# DNF
sudo dnf copr enable --assumeyes peterwu/iosevka
sudo dnf install --assumeyes papirus-icon-theme iosevka-curly-fonts ibus-unikey


# Flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

utilities='org.gnome.Extensions com.usebottles.bottles org.js.nuclear.Nuclear'
tools='com.visualstudio.code org.blender.Blender org.godotengine.Godot'
games='com.valvesoftware.Steam org.libretro.RetroArch org.polymc.PolyMC sh.ppy.osu'
flatpak install --assumeyes flathub $utilities $tools $games


# Homebrew
bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" # TODO improve

brew install ruby nushell micro p7zip ffmpeg imagemagick gifski asciinema


# Config ------------------------------------------------------------------------------------------

# Gnome
gsettings set org.gnome.desktop.interface icon-theme Papirus

bash -c "$(curl -fsSL https://raw.githubusercontent.com/rafaelmardojai/firefox-gnome-theme/master/scripts/install-by-curl.sh)"


# Git
git config --global user.email nnbnh@protonmail.com
git config --global user.name NNB
git config --global credential.helper store
git config --global pull.rebase true

mkdir -p ~/.local/share
curl -fsSL https://raw.githubusercontent.com/GitAlias/gitalias/main/gitalias.txt > ~/.local/share/gitalias.txt
git config --global include.path ~/.local/share/gitalias.txt


# NuShell
echo '# TODO NuShell'


# Micro
mkdir -p ~/.config/micro
printf '%s' '{ "colorscheme": "geany", "mkparents": true, "rmtrailingws": true }' > ~/.config/micro/settings.json
