#!/bin/sh

#    ____    __
#   / __/__ / /___ _____
#  _\ \/ -_) __/ // / _ \
# /___/\__/\__/\_,_/ .__/
#                 /_/

# File:         setup
# Description:  setup script that SuperB
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/dots/blob/master/setup


# Values
DOTS=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
XDG_DATA_HOME="$HOME/.local/share"


# Install packages
curl -fsSL https://raw.githubusercontent.com/NNBnh/bawkpack/master/bawkpack --create-dirs -o "$DOTS/bawkpack" && chmod +x "$DOTS/bawkpack"
"$DOTS/bawkpack" "$DOTS/packageslist"


# Before symlink
	# Create directories (to only symlink files inside, not the directory)
	mkdir "$HOME/.local/bin" "$HOME/.config/fish" "$HOME/.config/kak" "$HOME/.config/retroarch"

	# Remove junks (Spring cleaning your $HOME)
	mkdir "$HOME/test"
	mv "$HOME/Desktop" "$HOME/Documents" "$HOME/Downloads" "$HOME/Music" "$HOME/Pictures" "$HOME/Public" "$HOME/Templates" "$HOME/Videos" "$HOME/.ICEauthority" "$HOME/.bash_history" "$HOME/.bash_logout" "$HOME/.bash_profile" "$HOME/.bashrc" "$HOME/.inputrc" "$HOME/.xinitrc" "$HOME/.xsession" "$HOME/.xsession-errors" "$HOME/test"


# Symlink dotfiles
stow -vt ~ home
sudo stow -vt / root


# After symlink
	# Change default shell
	chsh -s /usr/bin/fish

	# Enable firewall
	sudo ufw enable

	# Git-alias
	curl -fsSL https://raw.githubusercontent.com/GitAlias/gitalias/master/gitalias.txt --create-dirs -o "$XDG_DATA_HOME/git/gitalias.txt"

	# Wallpaper
	git clone https://github.com/NNBnh/wallpaper-collections.git "$XDG_DATA_HOME/wallpapers"

	# Textart
	git clone https://github.com/NNBnh/textart-collections.git "$XDG_DATA_HOME/textart"

	# Bfetch
	git clone https://github.com/NNBnh/bfetch.git "$XDG_DATA_HOME/bfetch"
	ln -s "$XDG_DATA_HOME/bfetch/bfetch" "$HOME/.local/bin/"

	# Vimv
	git clone https://github.com/thameera/vimv.git "$XDG_DATA_HOME/vimv"
	ln -s "$XDG_DATA_HOME/vimv/vimv" "$HOME/.local/bin/"


exit 0
