#!/bin/sh

#    ____    __
#   / __/__ / /___ _____
#  _\ \/ -_) __/ // / _ \
# /___/\__/\__/\_,_/ .__/
#                 /_/

# File:         setup
# Description:  setup script that SuperB
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/dots/blob/master/setup


# Values
DOTS=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

. "$DOTS/home/.config/env" # Get my environment variables

bawkpack_location="$DOTS/extra/bawkpack"


# Install packages
curl -fsSL https://raw.githubusercontent.com/NNBnh/superb-bootstrap/master/extra/bawkpack --create-dirs --output "$bawkpack_location" && chmod +x "$DOTS/bawkpack"
"$bawkpack_location" "$DOTS/packageslist"


# Before symlink
	# Create directories (to only symlink files inside, not the directory)
	mkdir "$HOME/.config" "$HOME/.config/fcitx" "$HOME/.config/fish" "$HOME/.config/kak" "$HOME/.config/retroarch" \
	      "$HOME/.local" "$HOME/.local/bin" "$HOME/.local/share" \
	      "$HOME/.cache"

	# Remove junks (Spring cleaning your $HOME)
	mkdir "$HOME/test"
	mv "$HOME/Desktop" "$HOME/Documents" "$HOME/Downloads" "$HOME/Music" "$HOME/Pictures" "$HOME/Public" "$HOME/Templates" "$HOME/Videos" "$HOME/.ICEauthority" "$HOME/.bash_history" "$HOME/.bash_logout" "$HOME/.bash_profile" "$HOME/.bashrc" "$HOME/.inputrc" "$HOME/.xinitrc" "$HOME/.xsession" "$HOME/.xsession-errors" "$HOME/test"


# Symlink dotfiles
stow -vt ~ home
sudo stow -vt / root


# After symlink
	# Install extra packages
		# Python packages
		pip install --upgrade auto-editor git+https://github.com/will8211/unimatrix.git

		# BUI terminal
		git clone https://github.com/NNBnh/bui-terminal.git "$XDG_DATA_HOME/bui-terminal" && ln -fs "$XDG_DATA_HOME/bui-terminal/bui-terminal" "$HOME/.local/bin/"

		# Bfetch
		git clone https://github.com/NNBnh/bfetch.git "$XDG_DATA_HOME/bfetch" && ln -fs "$XDG_DATA_HOME/bfetch/bfetch" "$HOME/.local/bin/"

		# Fetchutils
		git clone https://github.com/lptstr/fetchutils.git "$XDG_DATA_HOME/fetchutils"

		# Wallpapers
		git clone https://github.com/NNBnh/wallpaper-collections.git "$XDG_DATA_HOME/wallpapers"

		# Textarts
		git clone https://github.com/NNBnh/textart-collections.git "$XDG_DATA_HOME/textart"

		# Figlet fonts
		git clone https://github.com/xero/figlet-fonts.git "$XDG_DATA_HOME/figlet/fonts"

		# Git enhancements
		curl -fsSL https://raw.githubusercontent.com/GitAlias/gitalias/master/gitalias.txt --create-dirs --output "$XDG_DATA_HOME/git/gitalias.txt"
		curl -fsSL https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json --create-dirs --output "$XDG_DATA_HOME/git/gitmojis.json"

	# Setup
		# Change default shell
		chsh -s /usr/bin/fish

		# Change XDG directories
		xdg-user-dirs-update --set DESKTOP     "$XDG_DESKTOP_DIR"
		xdg-user-dirs-update --set DOCUMENTS   "$XDG_DOCUMENTS_DIR"
		xdg-user-dirs-update --set DOWNLOAD    "$XDG_DOWNLOAD_DIR"
		xdg-user-dirs-update --set MUSIC       "$XDG_MUSIC_DIR"
		xdg-user-dirs-update --set PICTURES    "$XDG_PICTURES_DIR"
		xdg-user-dirs-update --set PUBLICSHARE "$XDG_PUBLICSHARE_DIR"
		xdg-user-dirs-update --set TEMPLATES   "$XDG_TEMPLATES_DIR"
		xdg-user-dirs-update --set VIDEOS      "$XDG_VIDEOS_DIR"

		# Enable firewall
		sudo ufw enable

		# Fontconfig
		fc-cache --really-force

		# Firefox CSS
		for profile in $HOME/.mozilla/firefox/*.default-release; do
			ln -fs "$DOTS/extra/firefox/chrome" "$profile/"
		done && echo 'Remember to enable the option toolkit.legacyUserProfileCustomizations.stylesheets in about:config'


exit 0
