#!/bin/sh

#     ____  __   _____
#    / __ )/ /  / ___/
#   / __  / /   \__ \
#  / /_/ / /______/ /
# /_____/_____/____/
#

# File:         bls
# Description:  List file that SuperB
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/dots/blob/master/home/.local/bin/bls
# License:      GPLv3

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


# Values
RAW_MODE="${1:-false}"

[ "$RAW_MODE" != 'true' ] && {
	ICONS='true'
	STYLE='true'
}

for file in .* *; do
	if [ -h "$file" ]; then
		check=$(readlink "$file")
	else
		check="$file"
	fi

	if [ -d "$check" ]; then
		directories="${directories:+$directories\n}${STYLE:+\033[1m}${ICONS:+📁}$file\033[0m"
	elif [ -e "$check" ] || [ -h "$file" ]; then
		files="${files:+$files\n}${STYLE:+\033[0m}${ICONS:+📄}$file\033[0m"
	fi
done


# Start
printf "${directories:+$directories\n}$files"


exit 0
