#!/bin/sh

#    _______ __                      __
#   / ____(_) /_   ____  __  _______/ /_
#  / / __/ / __/  / __ \/ / / / ___/ __ \
# / /_/ / / /_   / /_/ / /_/ (__  ) / / /
# \____/_/\__/  / .___/\__,_/____/_/ /_/
#              /_/
#    ____        _      __
#   / __ \__  __(_)____/ /__
#  / / / / / / / / ___/ //_/
# / /_/ / /_/ / / /__/ ,<
# \___\_\__,_/_/\___/_/|_|
#

# File:         git-pushq
# Description:  Git push quick
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/dots/blob/master/home/.local/bin/git-pushq
# License:      GPLv3

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


# Values
BRANCH_NAME=$(git branch-name)

MESSAGE="$*"


# Start
git add --all
git commit --message "$MESSAGE"
git pull origin "$BRANCH_NAME"
git push origin "$BRANCH_NAME"


exit 0
