#!/bin/sh

#    __ __         __
#   / // /__ _____/ /_____ ______ _  ___ ____ 
#  / _  / _ `/ __/  '_/ -_) __/  ' \/ _ `/ _ \
# /_//_/\_,_/\__/_/\_\\__/_/ /_/_/_/\_,_/_//_/

# File:         hackerman
# Description:  Script for hackerman
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/dots/wiki/hackerman
# License:      GPLv3

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


# Values
	# Action
	case "$1" in
		'i'|'ip')               ACTION="curl --silent --location 'ifconfig.co/json'"                                                              ;;
		'c'|'currency'|'money') ACTION="curl --silent --location 'rate.sx'"                                                                       ;;
		'r'|'rate')             ACTION="curl --silent --location 'rate.sx/btc'"                                                                   ;;
		'w'|'weather')          ACTION="curl --silent --location 'wttr.in'"                                                                       ;;
		'2'|'weather2')         ACTION="curl --silent --location 'V2.wttr.in'"                                                                    ;;
		'a'|'attack')           ACTION="printf '%s' 'curl --silent --location 'http://bit.ly/10hA8iC' | bash'"                                    ;;
		'R'|'run'|'rick')       ACTION="curl --silent --location 'https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh' | bash" ;;
		'S'|'sneakers')         ACTION="sneakers"                                                                                                 ;;
		'A'|'map')              ACTION="telnet 'mapscii.me'"                                                                                      ;;
		'I'|'info'|'system')
			if [ -n "$(command -v htop)" ]; then
				ACTION="htop"
			else
				ACTION="top"
			fi
		;;
		*)
			if [ -n "$(command -v unimatrix)" ]; then
				ACTION="unimatrix -s 96"
			else
				ACTION="cmatrix"
			fi
		;;
	esac

	# Effect
	case "$2" in
		'd'|'n'|'decrypt'|'nms') EFFECT="sed -e 's/\x1B\[[0-9;]*[JKmsu]//g' | nms -a" ;;
	esac


# Start
eval "$ACTION${EFFECT:+ | $EFFECT}"


exit 0
