#!/bin/sh

# File:         lsdwim
# Description:  LS DWIM
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/dots/blob/master/home/.local/bin/lsdwim
# License:      GPLv3


# Values
TMPDIR="${TMPDIR:-/tmp}"

ID="${1:-test}"

LS="$(eval "$SHELL -c 'l'")
[0m"

TEMPORARY="${LSDWIM_TEMPORARY:-$TMPDIR/lsdwim}"


# Start
[ "$LS" != "$(< "$TEMPORARY/$ID")" ] && {
	mkdir -p "$TMPDIR/lsdwim"
	printf "$LS" | tee "$TEMPORARY/$ID"
}


exit 0
