#!/bin/sh


# Values
eval "$("$HOME/.config/env/rc")"

WM_DIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

up_cua='Up'
down_cua='Down'
left_cua='Left'
right_cua='Right'
up_key='i'
down_key='k'
left_key='j'
right_key='l'

workspace01_cua='1'
workspace02_cua='2'
workspace03_cua='3'
workspace04_cua='4'
workspace05_cua='5'
workspace06_cua='6'
workspace07_cua='7'
workspace08_cua='8'
workspace09_cua='9'
workspace10_cua='0'
workspace01_key='a'
workspace02_key='s'
workspace03_key='d'
workspace04_key='f'
workspace05_key='g'
workspace06_key='q'
workspace07_key='w'
workspace08_key='e'
workspace09_key='r'
workspace10_key='t'

config="$config
	floating_modifier Mod4

	bindsym button2 kill
	bindsym       button3 exec \"$WM_DIR/floatdwim next\"
	bindsym Shift+button3 exec \"$WM_DIR/floatdwim prev\"

	bindsym Mod4+Space exec \"$WM_DIR/info\"

	bindsym Mod4+Escape exec \"$WM_DIR/lock\"
	bindsym Mod4+Shift+Escape exec \"exit\"
	bindsym Mod4+Alt+Escape reload
"

for key_type in 'arrow' 'character'; do
	for direction in 'up' 'down' 'left' 'right'; do
		case "$key_type" in
			'arrow')     key=$(eval "printf '%s' \"\$${direction}_cua\"") ;;
			'character') key=$(eval "printf '%s' \"\$${direction}_key\"") ;;
		esac

		case "$direction" in
			'up')    resize='shrink height' ;;
			'down')  resize='grow   height' ;;
			'left')  resize='shrink width ' ;;
			'right') resize='grow   width ' ;;
		esac

		config="$config
			bindsym Mod4+$key       focus  $direction
			bindsym Mod4+Alt+$key   move   $direction $(( ${BUI_GAPS_SIZE%%.*} / 2 ))px
			bindsym Mod4+Shift+$key resize $resize    $(( ${BUI_GAPS_SIZE%%.*} / 2 ))px
			bindsym Mod4+Ctrl+$key  resize $resize                                  1px
		"
	done
done

for key_type in 'number' 'character'; do
	for workspace in '01' '02' '03' '04' '05' '06' '07' '08' '09' '10'; do
		case "$key_type" in
			'number')    key=$(eval "printf '%s' \"\$workspace${workspace}_cua\"") ;;
			'character') key=$(eval "printf '%s' \"\$workspace${workspace}_key\"") ;;
		esac

		config="$config
			bindsym Mod4+$key           exec \"$WM_DIR/wmdwim $workspace next false\"
			bindsym Mod4+Shift+$key     exec \"$WM_DIR/wmdwim $workspace prev false\"
			bindsym Mod4+Alt+$key       exec \"$WM_DIR/wmdwim $workspace next true\"
			bindsym Mod4+Shift+Alt+$key exec \"$WM_DIR/wmdwim $workspace prev true\"
		"
	done
done

config="$config
	bindsym Mod4+equal                exec \"pactl set-sink-volume 0 +5%\"
	bindsym Mod4+minus                exec \"pactl set-sink-volume 0 -5%\"
	bindsym Mod4+apostrophe           exec \"pactl set-sink-mute 0 toggle\"

	bindsym Mod4+Ctrl+equal           exec \"playerctl volume 0.05+\"
	bindsym Mod4+Ctrl+minus           exec \"playerctl volume 0.05-\"
	bindsym Mod4+Ctrl+apostrophe      exec \"playerctl play-pause\"

	bindsym Mod4+Shift+equal          exec \"brightnessctl set +5%\"
	bindsym Mod4+Shift+minus          exec \"brightnessctl set -5%\"
	bindsym Mod4+Shift+apostrophe     exec \"brightnessctl set 1%\"

	bindsym Mod4+Alt+equal            exec \"pactl set-source-volume 0 +5%\"
	bindsym Mod4+Alt+minus            exec \"pactl set-source-volume 0 -5%\"
	bindsym Mod4+Alt+apostrophe       exec \"pactl set-source-mute 0 toggle\"

	bindsym Mod4+Alt+Ctrl+equal       opacity plus  0.1
	bindsym Mod4+Alt+Ctrl+minus       opacity minus 0.1
	bindsym Mod4+Alt+Ctrl+apostrophe  resize set width 50ppt height 50ppt

	bindsym Mod4+Slash exec \"$TERMINAL\"
	bindsym Mod4+Alt+Slash split toggle

	bindsym Mod4+x kill

	bindsym Mod4+c      exec \"screeny output\"
	bindsym Mod4+Ctrl+c exec \"screeny region\"
	bindsym Mod4+Alt+c  exec \"screeny color\"

	bindsym Mod4+v exec \"fcitx-remote -t\"

	bindsym Mod4+b focus mode_toggle
	bindsym Mod4+Alt+b       exec \"$WM_DIR/floatdwim next\"
	bindsym Mod4+Alt+Shift+b exec \"$WM_DIR/floatdwim prev\"

	bindsym Mod4+z      focus parent
	bindsym Mod4+Ctrl+z focus child

	bindsym Mod4+Backslash       layout toggle tabbed splith splitv
	bindsym Mod4+Shift+Backslash layout toggle splitv splith tabbed
	bindsym Mod4+Alt+Backslash fullscreen
"

printf '%s' "$config"


exit 0
