#!/bin/sh


# Values
eval "$("$HOME/.config/env/rc")"

WM_DIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)


# Start
printf '%s' "
	workspace_layout tabbed

	smart_gaps on
	smart_borders no_gaps
	title_align center

	font \"pango:$BUI_FONT_FAMILY ${BUI_FONT_SIZE%%.*}\"

	gaps inner all set \"$(( ${BUI_GAPS_SIZE%%.*} - ( ${BUI_BORDER_SIZE%%.*} * 2 ) ))px\"
	gaps outer all set \"${BUI_BORDER_SIZE%%.*}px\"

	default_border normal \"${BUI_BORDER_SIZE%%.*}px\"
	titlebar_border_thickness \"${BUI_BORDER_SIZE%%.*}\"
	titlebar_padding \"${BUI_GAPS_SIZE%%.*} ${BUI_BORDER_SIZE%%.*}\"

	client.focused          \"$BUI_COLOR_CURSOR\"    \"$BUI_COLOR_CURSOR\"    \"$BUI_COLOR_BACKGROUND\" \"$BUI_COLOR_CURSOR_ALT\" \"$BUI_COLOR_CURSOR\"
	client.focused_inactive \"$BUI_COLOR_SELECTION\" \"$BUI_COLOR_SELECTION\" \"$BUI_COLOR_FOREGROUND\" \"$BUI_COLOR_CURSOR_ALT\" \"$BUI_COLOR_SELECTION\"
	client.unfocused        \"$BUI_COLOR_SELECTION\" \"$BUI_COLOR_SELECTION\" \"$BUI_COLOR_FOREGROUND\" \"$BUI_COLOR_CURSOR_ALT\" \"$BUI_COLOR_SELECTION\"
	client.urgent           \"$BUI_COLOR_BASE08\"    \"$BUI_COLOR_BASE08\"    \"$BUI_COLOR_BACKGROUND\" \"$BUI_COLOR_CURSOR_ALT\" \"$BUI_COLOR_BASE08\"

	focus_follows_mouse no
	focus_wrapping      no

	$($WM_DIR/bmap)
"


# killall -p swayidle; swayidle -w before-sleep "$WM_DIR/lock" \
#                                       timeout $(( 15 * 60 )) "$WM_DIR/lock; $MSG_COMMAND output * dpms off" \
#                                        resume "$MSG_COMMAND output * dpms on" &


exit 0
