# Options
prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "custom.icon",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "docker_context",
    "package",
    "dotnet",
    "elixir",
    "elm",
    "erlang",
    "golang",
    "haskell",
    "java",
    "julia",
    "nim",
    "nodejs",
    "ocaml",
    "php",
    "purescript",
    "python",
    "ruby",
    "rust",
    "terraform",
    "zig",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "crystal",
    "cmd_duration",
    "custom",
    "jobs",
    "battery",
    "line_break",
    "time",
    "character",
]


# Module
[custom.icon]
disabled = false
when = ""
command = "echo "
symbol = " "
prefix = "in "
style = ""

[directory]
disabled = false
prefix = " "
style = "bright-white bold"

[time]
disabled = false
format = " %r "
style = "bg:bright-yellow fg:black bold"

[character]
disabled = false
# symbol = ""
symbol = "$"
vicmd_symbol = "█"
style_success = "bright-yellow bold"
style_failure = "red bold"


# Icons
[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

