#!/bin/sh


# Values
FILE="$XDG_DATA_HOME/textart/color/strip.textart"
WIDTH='4'

i='0'

while [ $(( i + 1 )) -le "$WIDTH" ] && [ $(( ( i + 1 ) * 8 )) -le "$BFETCH_COLOR_WIDTH" ]; do
	TEXT="$TEXT "

	i=$(( i + 1 ))
done

[ "$BFETCH_COLOR_HEIGHT" -lt '2' ] && MODES='normal'


# Start
[ -x "$FILE" ] && $FILE "\033[7m$TEXT" "$MODES"


exit 0
