#!/bin/sh


# Values
COLOR="${BUI_COLOR_TEXTART:-32}"
OS=$("$XDG_DATA_HOME"/fetchutils/src/os.sh 2>&- | sed -e 's/^[[:lower:]]/\U&/g'); [ -n "$OS" ] && [ "${#OS}" -gt '16' ] && OS='Void Linux'
WM=$("$XDG_DATA_HOME"/fetchutils/src/wm.sh 2>&- | sed -e 's/^[[:lower:]]/\U&/g'); [ -n "$WM" ] && [ "${#WM}" -gt '16' ] && WM='Sway'
SHELL=$(basename "$SHELL" | sed 's/^[[:lower:]]/\U&/g')
TERMINAL=$(basename "$TERMINAL" | sed 's/^[[:lower:]]/\U&/g')
FONT="$BUI_FONT_MONO_FAMILY"


# Start
printf "\033[1;${COLOR}mOS        \033[0m💾${OS:-OS}\033[0m
\033[1;${COLOR}mWM        \033[0m🖼️${WM:-WM}\033[0m
\033[1;${COLOR}mSHELL     \033[0m🐚${SHELL:-Shell}\033[0m
\033[1;${COLOR}mTERMINAL  \033[0m📟${TERMINAL:-Terminal}\033[0m
\033[1;${COLOR}mFONT      \033[0m🏷️${FONT:-Font}\033[0m"


exit 0
