#!/bin/sh


# Values
COLOR="${BUI_COLOR_TEXTART:-32}"
OS=$($XDG_DATA_HOME/fetchutils/src/os.sh)
SHELL=$(basename "$SHELL" | sed 's/^[[:lower:]]/\U&/g')
WM='Sway'
TERMINAL=$(basename "$TERMINAL" | sed 's/^[[:lower:]]/\U&/g')
FONT='Iosevka'


# Start
printf "\033[1;${COLOR}mOS        \033[0m${OS:-os}\033[0m
\033[1;${COLOR}mWM        \033[0m${WM:-wm}\033[0m
\033[1;${COLOR}mSHELL     \033[0m${SHELL:-shell}\033[0m
\033[1;${COLOR}mTERMINAL  \033[0m${TERMINAL:-terminal}\033[0m
\033[1;${COLOR}mFONT      \033[0m${FONT:-font}\033[0m"


exit 0
