#!/bin/sh


# Values
COLOR="${BUI_COLOR_TEXTART:-32}"
OS=$("$HOME/c/extra/fetchutils/src/os.sh" 2>&- | tr '[:upper:]' '[:lower:]'); [ -n "$OS" ] && [ "${#OS}" -gt '16' ] && OS='Linux'
WM=$("$HOME/c/extra/fetchutils/src/wm.sh" 2>&- | tr '[:upper:]' '[:lower:]'); [ -n "$WM" ] && [ "${#WM}" -gt '16' ] && WM='River'
SHELL=$(basename "$SHELL" | tr '[:upper:]' '[:lower:]')
TERMINAL=$(basename "$TERMINAL" | tr '[:upper:]' '[:lower:]')
FONT="$BUI_FONT_MONO_FAMILY"


# Start
printf "\033[1;${COLOR}mOS        \033[0m💾${OS:-OS}\033[0m
\033[1;${COLOR}mWM        \033[0m🖼️${WM:-WM}\033[0m
\033[1;${COLOR}mSHELL     \033[0m🐚${SHELL:-Shell}\033[0m
\033[1;${COLOR}mTERMINAL  \033[0m📟${TERMINAL:-Terminal}\033[0m
\033[1;${COLOR}mFONT      \033[0m🏷️${FONT:-Font}\033[0m"


exit 0
