#!/bin/sh


# Links
ln -sf "$HOME/Dotfiles/home/.local/share/themes" "$HOME/.themes"

# Grub theme
git clone https://github.com/mateosss/matter.git "$HOME/.local/share/grub/themes/matter"

# Git
	# Login
	read -p '(Git) Enter your name: ' install_git_name \
		&& git config --global user.name "${install_git_name}"
	read -p '(Git) Enter your email: ' install_git_email \
		&& git config --global user.email "${install_git_email}"

	# Git-alias 
	mkdir -p "$HOME/.local/share/git" \
		&& curl -fsSL https://raw.githubusercontent.com/GitAlias/gitalias/master/gitalias.txt \
			> "$HOME/.local/share/git/gitalias.txt" \
		&& git config --global include.path '.local/share/git/gitalias.txt'
# Making Zsh to default shell
chsh -s "/usr/bin/zsh"

# Enable firewall
sudo ufw enable


exit
