#!/bin/sh


# Values
eval "$("$HOME/.config/env/rc")"


# Start
killall -p swaybg; swaybg --mode "$WALLPAPER_MODE" --image "$WALLPAPER_FILE" &

killall -p dunst; eval "dunst $DUNST_DEFAULT_OPTS"

bui-appearance


exit 0
