#!/bin/sh


# Values
PROMPT_COLOR="${BUI_COLOR_TEXTART:-15}"

[ "$DIYSHIP_DURATION" -gt '2000' ] && DURATION="\033[30mtook \033[1m$(ms2duration "$DIYSHIP_DURATION")"

[ "$DIYSHIP_STATUS" -gt '0' ] && {
	# case "$DIYSHIP_STATUS" in
	# 	'126') STATUS_SYMBOL='🚫' ;;
	# 	'127') STATUS_SYMBOL='🔍' ;;
	# 	'130') STATUS_SYMBOL='🧱' ;;
	# 	*)     STATUS_SYMBOL='⚡' ;;
	# esac

	STATUS="\033[1;30m$(status2signal "$DIYSHIP_STATUS"):$DIYSHIP_STATUS"
}

[ -d "$PWD/.git" ] && {
	GIT_BRANCH=$(git rev-parse --abbrev-ref 'HEAD' 2>/dev/null) \
	&& GIT_BRANCH="on \033[1;95m $GIT_BRANCH"

	git symbolic-ref 'HEAD' 2>&1 >/dev/null || {
		GIT_HASH=$(git rev-parse --verify --short 'HEAD' 2>/dev/null) \
		&& GIT_HASH="\033[1;92m#$GIT_HASH"
	}

	GIT_TAG=$(git tag --points-at 'HEAD' 2>/dev/null) \
	&& [ -n "$GIT_TAG" ] && GIT_TAG="\033[1;93m🏷 $GIT_TAG"
}

[ "$DIYSHIP_JOBS" -gt '0' ] && JOBS="\033[1;30m$DIYSHIP_JOBS&"

INFO=$(
	POWERBG_LEFTEND_OUTER=' ' \
	POWERBG_LEFTEND_INNER=' ' \
	POWERBG_RIGHTEND_OUTER=' ' \
	POWERBG_RIGHTEND_INNER=' ' \
	POWERBG_SEPARATOR_LEFT=' ' \
	POWERBG_SEPARATOR_RIGHT=' ' \
	POWERBG_SEPARATOR_SAME=' \033[90m ' \
	powerbg '1' "$STATUS" '3' "$DURATION" '0' "$GIT_BRANCH" '0' "$GIT_HASH" '0' "$GIT_TAG" '12' "$JOBS"
)

case "$PWD/" in
	"$HOME/d/"*) CWD_SYMBOL='🗃 ' ;;
	"$HOME/c/"*) CWD_SYMBOL='⚙ ' ;;
	"$HOME/t/"*) CWD_SYMBOL='⚗ ' ;;
	"$HOME/")    CWD_SYMBOL='🏠' ;;
	"$HOME/"*)   CWD_SYMBOL='📂' ;;
	*)           CWD_SYMBOL='📁' ;;
esac


# Start
printf '\033[4:3;58:5:7m%*s\033[0m%b\n%b\033[0m\n%b\033[0m ' \
       $(( ${COLUMNS:-$(tput cols)} - $(printf '%b' "$INFO" | sed -e 's/\x1b\[[0-9;:]*[a-zA-Z]//g' | wc --chars) )) '' "$INFO" \
	   " $CWD_SYMBOL$(PATHSHORTENER_TRUNCATION_LENGTH='0' pathshortener "$PWD")" \
       "\033[1;7${PROMPT_COLOR:+;38;5;$PROMPT_COLOR}m $(date +'%r') \033[0${PROMPT_COLOR:+;38;5;$PROMPT_COLOR}m"


exit 0
