#!/bin/sh


# Values
. "$HOME/.config/env"

SWAY_DIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)


# Start
swaymsg smart_gaps yes
swaymsg smart_borders no_gaps
swaymsg title_align center

swaymsg font "pango:$BUI_FONT_FAMILY ${BUI_FONT_SIZE%%.*}"

swaymsg gaps inner all set "$(( ${BUI_GAPS_SIZE%%.*} - ( ${BUI_BORDER_SIZE%%.*} * 2 ) ))px"
swaymsg gaps outer all set "${BUI_GAPS_SIZE%%.*}px"

swaymsg default_border normal "${BUI_BORDER_SIZE%%.*}px"
swaymsg titlebar_border_thickness "${BUI_BORDER_SIZE%%.*}"
swaymsg titlebar_padding "${BUI_GAPS_SIZE%%.*} ${BUI_BORDER_SIZE%%.*}"

swaymsg client.focused          "$BUI_COLOR_CURSOR"    "$BUI_COLOR_CURSOR"    "$BUI_COLOR_BACKGROUND" "$BUI_COLOR_CURSOR_ALT" "$BUI_COLOR_CURSOR"
swaymsg client.focused_inactive "$BUI_COLOR_SELECTION" "$BUI_COLOR_SELECTION" "$BUI_COLOR_FOREGROUND" "$BUI_COLOR_CURSOR_ALT" "$BUI_COLOR_SELECTION"
swaymsg client.unfocused        "$BUI_COLOR_SELECTION" "$BUI_COLOR_SELECTION" "$BUI_COLOR_FOREGROUND" "$BUI_COLOR_CURSOR_ALT" "$BUI_COLOR_SELECTION"
swaymsg client.urgent           "$BUI_COLOR_BASE08"    "$BUI_COLOR_BASE08"    "$BUI_COLOR_BACKGROUND" "$BUI_COLOR_CURSOR_ALT" "$BUI_COLOR_BASE08"

swaymsg focus_follows_mouse no
swaymsg focus_wrapping      no

$SWAY_DIR/bmap


xdg-user-dirs-update --set DESKTOP "$XDG_DESKTOP_DIR"
xdg-user-dirs-update --set DOCUMENTS "$XDG_DOCUMENTS_DIR"
xdg-user-dirs-update --set DOWNLOAD "$XDG_DOWNLOAD_DIR"
xdg-user-dirs-update --set MUSIC "$XDG_MUSIC_DIR"
xdg-user-dirs-update --set PICTURES "$XDG_PICTURES_DIR"
xdg-user-dirs-update --set PUBLICSHARE "$XDG_PUBLICSHARE_DIR"
xdg-user-dirs-update --set TEMPLATES "$XDG_TEMPLATES_DIR"
xdg-user-dirs-update --set VIDEOS "$XDG_VIDEOS_DIR"


gsettings set org.gnome.desktop.interface gtk-theme  'Matcha-dark-aliz'
gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
gsettings set org.gnome.desktop.interface font-name  "$BUI_FONT_FAMILY ${BUI_FONT_SIZE%%.*}"


swaybg --mode fill --image "$XDG_DATA_HOME/wallpapers/johnn21/brown-wooden-table-and-chairs-near-white-concrete-building-during-daytime.jpg" &

killall -p waybar; waybar &

killall -p mako; mako --max-visible='8' \
                      --default-timeout='3000' \
                      --anchor "top-right" \
                      --font "$BUI_FONT_FAMILY ${BUI_FONT_SIZE%%.*}" \
                      --margin="$(( ${BUI_GAPS_SIZE%%.*} - ( ${BUI_BORDER_SIZE%%.*} * 2 ) ))" \
                      --padding="$(( ${BUI_GAPS_SIZE%%.*} - ( ${BUI_BORDER_SIZE%%.*} * 2 ) ))" \
                      --border-size "${BUI_BORDER_SIZE%%.*}" \
                      --text-color "$BUI_COLOR_FOREGROUND" \
                      --background-color "$BUI_COLOR_BACKGROUND" \
                      --border-color "$BUI_COLOR_CURSOR" \
                      --progress-color "$BUI_COLOR_CURSOR" &

killall -p swayidle; swayidle -w before-sleep "$SWAY_DIR/lock --daemonize" \
            timeout $(( 15 * 60 )) "$SWAY_DIR/lock --daemonize; swaymsg 'output * dpms off'" \
            resume "swaymsg 'output * dpms on'" &


exit 0
