#!/bin/sh


# Values
. "$HOME/.config/env"

SWAY_DIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)


# Start
swaymsg smart_gaps on
swaymsg smart_borders no_gaps
swaymsg title_align center

swaymsg font "pango:$BUI_FONT_FAMILY ${BUI_FONT_SIZE%%.*}"

swaymsg gaps inner "$(( ${BUI_GAPS_SIZE%%.*} - ( ${BUI_BORDER_SIZE%%.*} * 2 ) ))px"
swaymsg gaps outer "${BUI_BORDER_SIZE%%.*}px"

swaymsg default_border normal "${BUI_BORDER_SIZE%%.*}px"
swaymsg titlebar_border_thickness "${BUI_BORDER_SIZE%%.*}"
swaymsg titlebar_padding "${BUI_GAPS_SIZE%%.*} ${BUI_BORDER_SIZE%%.*}"

swaymsg client.focused          "$BUI_COLOR_CURSOR"    "$BUI_COLOR_CURSOR"    "$BUI_COLOR_BACKGROUND" "$BUI_COLOR_CURSOR_ALT" "$BUI_COLOR_CURSOR"
swaymsg client.focused_inactive "$BUI_COLOR_SELECTION" "$BUI_COLOR_SELECTION" "$BUI_COLOR_FOREGROUND" "$BUI_COLOR_CURSOR_ALT" "$BUI_COLOR_SELECTION"
swaymsg client.unfocused        "$BUI_COLOR_SELECTION" "$BUI_COLOR_SELECTION" "$BUI_COLOR_FOREGROUND" "$BUI_COLOR_CURSOR_ALT" "$BUI_COLOR_SELECTION"
swaymsg client.urgent           "$BUI_COLOR_BASE08"    "$BUI_COLOR_BASE08"    "$BUI_COLOR_BACKGROUND" "$BUI_COLOR_CURSOR_ALT" "$BUI_COLOR_BASE08"

swaymsg focus_follows_mouse no
swaymsg focus_wrapping      no

$SWAY_DIR/bmap

killall -p swayidle; swayidle -w before-sleep "$SWAY_DIR/lock" \
                                      timeout $(( 15 * 60 )) "$SWAY_DIR/lock; swaymsg output * dpms off" \
                                       resume "swaymsg output * dpms on" &


exit 0
